'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import { SnowfallIcon as SnowfallIconElement, defineCustomElement as defineSnowfallIcon } from "stencil-library/dist/components/snowfall-icon.js";

export type SnowfallIconEvents = NonNullable<unknown>;

export const SnowfallIcon: StencilReactComponent<SnowfallIconElement, SnowfallIconEvents> = /*@__PURE__*/ createComponent<SnowfallIconElement, SnowfallIconEvents>({
    tagName: 'snowfall-icon',
    elementClass: SnowfallIconElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SnowfallIconEvents,
    defineCustomElement: defineSnowfallIcon
});
