/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SnowfallIcon {
        /**
          * Название иконки
         */
        "name": string;
        /**
          * Вариант размера элемента
          * @default 'medium'
         */
        "size": number | 'xsmall' | 'small' | 'medium' | 'large';
    }
}
declare global {
    interface HTMLSnowfallIconElement extends Components.SnowfallIcon, HTMLStencilElement {
    }
    var HTMLSnowfallIconElement: {
        prototype: HTMLSnowfallIconElement;
        new (): HTMLSnowfallIconElement;
    };
    interface HTMLElementTagNameMap {
        "snowfall-icon": HTMLSnowfallIconElement;
    }
}
declare namespace LocalJSX {
    interface SnowfallIcon {
        /**
          * Название иконки
         */
        "name": string;
        /**
          * Вариант размера элемента
          * @default 'medium'
         */
        "size"?: number | 'xsmall' | 'small' | 'medium' | 'large';
    }
    interface IntrinsicElements {
        "snowfall-icon": SnowfallIcon;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "snowfall-icon": LocalJSX.SnowfallIcon & JSXBase.HTMLAttributes<HTMLSnowfallIconElement>;
        }
    }
}
